// 의료기기 빈출 공정 블록 라이브러리
// 각 블록은 자동으로 SOP/검사/인증 매핑을 생성합니다.

export const PROCESS_CATEGORIES = [
  { id: 'machining', name: '가공', en: 'Machining', icon: 'Cog', color: 'sky' },
  { id: 'cleaning', name: '세척', en: 'Cleaning', icon: 'Droplets', color: 'sky' },
  { id: 'assembly', name: '조립', en: 'Assembly', icon: 'Puzzle', color: 'amber' },
  { id: 'inspection', name: '검사', en: 'Inspection', icon: 'Search', color: 'leaf' },
  { id: 'sterilization', name: '멸균', en: 'Sterilization', icon: 'Sparkles', color: 'rust' },
  { id: 'packaging', name: '포장·라벨링', en: 'Packaging & Labeling', icon: 'Package', color: 'moss' },
]

export const PROCESS_BLOCKS = [
  // 가공
  {
    id: 'cnc-milling',
    name: 'CNC 밀링',
    en: 'CNC Milling',
    category: 'machining',
    desc: '5축 머시닝 센터로 형상 가공',
    inputs: ['소재 로트', '도면 Rev'],
    outputs: ['반제품 ID', '치수 데이터'],
    sopAuto: ['SOP-MFG-001 CNC 밀링 작업 표준'],
    inspections: ['치수 검사 (CMM)', '표면 거칠기'],
    standards: ['ISO 13485 §7.5.1', 'FDA 21 CFR 820.70(a)'],
    risks: ['치수 이탈 → R-001'],
  },
  {
    id: 'cnc-turning',
    name: 'CNC 선반',
    en: 'CNC Turning',
    category: 'machining',
    desc: '회전체 부품 가공 (스크류·핀 등)',
    inputs: ['바재 로트', '도면 Rev'],
    outputs: ['반제품 ID'],
    sopAuto: ['SOP-MFG-002 CNC 선반 작업 표준'],
    inspections: ['치수 검사', '나사부 검사'],
    standards: ['ISO 13485 §7.5.1', 'FDA 21 CFR 820.70(a)'],
    risks: ['치수 이탈 → R-001'],
  },
  {
    id: 'edm',
    name: '방전가공 (EDM)',
    en: 'EDM',
    category: 'machining',
    desc: '미세 형상·복잡 형상 가공',
    inputs: ['반제품', '전극 로트'],
    outputs: ['가공품'],
    sopAuto: ['SOP-MFG-003 EDM 작업 표준'],
    inspections: ['표면 검사', '치수 검사'],
    standards: ['ISO 13485 §7.5.1'],
    risks: ['표면 손상 → R-002'],
  },
  {
    id: 'laser-cutting',
    name: '레이저 절단',
    en: 'Laser Cutting',
    category: 'machining',
    desc: '얇은 시트·튜브 정밀 절단',
    inputs: ['시트 로트'],
    outputs: ['절단품'],
    sopAuto: ['SOP-MFG-004 레이저 절단 표준'],
    inspections: ['치수 검사', 'HAZ 검사'],
    standards: ['ISO 13485 §7.5.1'],
    risks: ['열영향부 변형 → R-003'],
  },

  // 세척
  {
    id: 'ultrasonic-clean',
    name: '초음파 세척',
    en: 'Ultrasonic Cleaning',
    category: 'cleaning',
    desc: '가공 후 절삭유·이물질 제거',
    inputs: ['가공품', '세척액'],
    outputs: ['세척품'],
    sopAuto: ['SOP-CLN-001 초음파 세척 표준'],
    inspections: ['잔류물 분석 (TOC/육안)'],
    standards: ['ISO 13485 §7.5.1', 'ISO 19227 (정형외과 임플란트 세척)'],
    risks: ['잔류 절삭유 → R-005'],
  },
  {
    id: 'passivation',
    name: '부동태화',
    en: 'Passivation',
    category: 'cleaning',
    desc: '스테인리스 표면 처리 (질산·구연산)',
    inputs: ['세척품', '처리액'],
    outputs: ['부동태화품'],
    sopAuto: ['SOP-CLN-002 부동태화 표준'],
    inspections: ['표면 분석 (XPS)', '내식성 시험'],
    standards: ['ASTM F86', 'ISO 13485 §7.5.1'],
    risks: ['표면 산화 불충분 → R-006'],
  },
  {
    id: 'final-cleaning',
    name: '최종 세척',
    en: 'Final Cleaning',
    category: 'cleaning',
    desc: '멸균 직전 청정실 내 최종 세척',
    inputs: ['반제품'],
    outputs: ['멸균 대기품'],
    sopAuto: ['SOP-CLN-003 최종 세척 표준', 'SOP-CLN-004 청정실 운영'],
    inspections: ['생물부담 시험', '엔도톡신'],
    standards: ['ISO 14644 (청정실)', 'ISO 11737-1 (생물부담)'],
    risks: ['생물부담 초과 → R-007'],
  },

  // 조립
  {
    id: 'manual-assembly',
    name: '수동 조립',
    en: 'Manual Assembly',
    category: 'assembly',
    desc: '작업자가 직접 조립',
    inputs: ['부품 BOM'],
    outputs: ['조립품'],
    sopAuto: ['SOP-ASM-001 조립 작업 표준'],
    inspections: ['외관 검사', '기능 검사'],
    standards: ['ISO 13485 §7.5.1', 'FDA 21 CFR 820.70'],
    risks: ['오조립 → R-010'],
  },
  {
    id: 'press-fit',
    name: '압입 조립',
    en: 'Press Fit',
    category: 'assembly',
    desc: '프레스로 부품 결합',
    inputs: ['부품 A', '부품 B'],
    outputs: ['압입품'],
    sopAuto: ['SOP-ASM-002 압입 작업 표준'],
    inspections: ['압입력 데이터', '치수 검사'],
    standards: ['ISO 13485 §7.5.6 (특별공정)'],
    risks: ['압입 불충분 → R-011'],
  },
  {
    id: 'welding',
    name: '용접',
    en: 'Welding',
    category: 'assembly',
    desc: '레이저·TIG 용접',
    inputs: ['부품'],
    outputs: ['용접품'],
    sopAuto: ['SOP-ASM-003 용접 표준', 'SOP-VAL-001 용접 밸리데이션'],
    inspections: ['외관 검사', '비파괴 검사 (X-ray/PT)'],
    standards: ['ISO 13485 §7.5.6 (특별공정)', 'AWS D18'],
    risks: ['용접 결함 → R-012'],
    isSpecialProcess: true,
  },

  // 검사
  {
    id: 'visual-inspection',
    name: '외관 검사',
    en: 'Visual Inspection',
    category: 'inspection',
    desc: '확대경·현미경 검사',
    inputs: ['검사 대상품'],
    outputs: ['합격품/부적합품'],
    sopAuto: ['SOP-QC-001 외관 검사 표준'],
    inspections: ['외관 결함 분류'],
    standards: ['ISO 13485 §8.2.4', 'FDA 21 CFR 820.80'],
    risks: ['결함 미검출 → R-020'],
  },
  {
    id: 'cmm-inspection',
    name: 'CMM 치수 검사',
    en: 'CMM Inspection',
    category: 'inspection',
    desc: '3차원 측정기로 정밀 치수 측정',
    inputs: ['가공품'],
    outputs: ['치수 측정 데이터'],
    sopAuto: ['SOP-QC-002 CMM 검사 표준'],
    inspections: ['도면 대비 GD&T'],
    standards: ['ISO 13485 §7.6 (측정장비 관리)', '21 CFR 820.72'],
    risks: ['치수 OOS → R-021'],
  },
  {
    id: 'functional-test',
    name: '기능 검사',
    en: 'Functional Test',
    category: 'inspection',
    desc: '제품 기능·성능 시험',
    inputs: ['완제품'],
    outputs: ['기능 시험 데이터'],
    sopAuto: ['SOP-QC-003 기능 검사 표준'],
    inspections: ['성능 사양 대비'],
    standards: ['ISO 13485 §8.2.4', 'IEC 60601-1 (해당 시)'],
    risks: ['기능 불충족 → R-022'],
  },
  {
    id: 'leak-test',
    name: '누설 검사',
    en: 'Leak Test',
    category: 'inspection',
    desc: '기밀성 시험 (헬륨·압력)',
    inputs: ['완제품'],
    outputs: ['누설 데이터'],
    sopAuto: ['SOP-QC-004 누설 시험 표준'],
    inspections: ['누설률 측정'],
    standards: ['ISO 13485 §8.2.4'],
    risks: ['누설 → R-023'],
  },

  // 멸균
  {
    id: 'eo-sterilization',
    name: 'EO 멸균',
    en: 'Ethylene Oxide Sterilization',
    category: 'sterilization',
    desc: '에틸렌옥사이드 가스 멸균',
    inputs: ['포장된 제품'],
    outputs: ['멸균품'],
    sopAuto: ['SOP-STR-001 EO 멸균 표준', 'SOP-VAL-002 EO 멸균 밸리데이션'],
    inspections: ['생물학적 지표 (BI)', '잔류 EO 시험', '에어링 검증'],
    standards: ['ISO 11135 (EO 멸균)', 'ISO 10993-7 (EO 잔류)', 'ISO 13485 §7.5.6'],
    risks: ['멸균 실패 → R-030', 'EO 잔류 → R-031'],
    isSpecialProcess: true,
  },
  {
    id: 'gamma-sterilization',
    name: '감마선 멸균',
    en: 'Gamma Irradiation',
    category: 'sterilization',
    desc: '감마선 조사 멸균 (외주 일반적)',
    inputs: ['포장된 제품'],
    outputs: ['멸균품'],
    sopAuto: ['SOP-STR-002 감마선 멸균 표준'],
    inspections: ['선량 측정 (Dosimetry)', '재료 영향 평가'],
    standards: ['ISO 11137 (방사선 멸균)', 'ISO 13485 §7.5.6'],
    risks: ['선량 부족 → R-032'],
    isSpecialProcess: true,
  },
  {
    id: 'steam-sterilization',
    name: '증기 멸균 (오토클레이브)',
    en: 'Steam Sterilization',
    category: 'sterilization',
    desc: '고압 증기 멸균',
    inputs: ['포장된 제품'],
    outputs: ['멸균품'],
    sopAuto: ['SOP-STR-003 증기 멸균 표준', 'SOP-VAL-003 멸균기 밸리데이션'],
    inspections: ['생물학적 지표', '온도/압력 기록'],
    standards: ['ISO 17665 (습열 멸균)', 'ISO 13485 §7.5.6'],
    risks: ['멸균 실패 → R-033'],
    isSpecialProcess: true,
  },

  // 포장·라벨링
  {
    id: 'primary-packaging',
    name: '1차 포장',
    en: 'Primary Packaging',
    category: 'packaging',
    desc: '제품 직접 접촉 포장 (멸균 배리어)',
    inputs: ['반제품', '포장재'],
    outputs: ['포장된 제품'],
    sopAuto: ['SOP-PKG-001 1차 포장 표준', 'SOP-VAL-004 포장 밸리데이션'],
    inspections: ['실링 강도', '기밀성', '낙하 시험'],
    standards: ['ISO 11607-1/-2 (멸균 의료기기 포장)', 'ASTM F88, F1929, F2096'],
    risks: ['포장 손상 → R-040', '멸균 무효화 → R-041'],
    isSpecialProcess: true,
  },
  {
    id: 'labeling',
    name: '라벨링',
    en: 'Labeling',
    category: 'packaging',
    desc: 'UDI·로트·유효기한 라벨 부착',
    inputs: ['포장품', '라벨 마스터'],
    outputs: ['라벨링 완료품'],
    sopAuto: ['SOP-PKG-002 라벨링 표준'],
    inspections: ['UDI 바코드 검증 (ISO/IEC 15415)', '라벨 정합성'],
    standards: [
      'ISO 13485 §7.5.1',
      '21 CFR 801 (FDA 라벨링)',
      'MDR Annex VI Part C (UDI)',
      'ISO/IEC 15459 (UDI)',
    ],
    risks: ['라벨 오류 → R-042'],
  },
  {
    id: 'secondary-packaging',
    name: '2차 포장 (박스)',
    en: 'Secondary Packaging',
    category: 'packaging',
    desc: '운송용 박스 포장',
    inputs: ['1차 포장품'],
    outputs: ['출하 대기품'],
    sopAuto: ['SOP-PKG-003 박스 포장 표준'],
    inspections: ['박스 외관', '동봉물 확인'],
    standards: ['ISO 13485 §7.5.5'],
    risks: ['혼입 → R-043'],
  },
]

// 카테고리별 블록 그룹화 헬퍼
export function blocksByCategory() {
  const map = {}
  PROCESS_CATEGORIES.forEach((c) => (map[c.id] = []))
  PROCESS_BLOCKS.forEach((b) => map[b.category].push(b))
  return map
}

export function getBlock(id) {
  return PROCESS_BLOCKS.find((b) => b.id === id)
}
